<?php
/**
 * @project  Investment Deals
 * @copyright © 2017 by ivoglent
 * @author ivoglent
 * @time  9/19/17.
 */


namespace ivoglent\content\manager\widgets;




use yii\web\JqueryAsset;
use yii\web\View;

class Editor extends \ivoglent\content\manager\Widget
{
    /**
     * Model of this attribute
     * @var Model $model
     */
    public $model;
    /**
     * Name of attribute
     * @var string $attribute
     */
    public $attribute;

    /** @var string  */
    public $value = '';

    /**
     * Name of hidden input if you want to use this widget
     * without a model
     * @var string $target
     */
    public $target;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        \Yii::$app->view->registerJsFile($this->assetUrl . '/scripts/tinymce.min.js', [
            'depends' => [JqueryAsset::className()],
            'position' => View::POS_HEAD
        ]);
    }

    public function run()
    {
        return $this->render('editor', []);
    }
}